name: Package Cleanup
on:
    workflow_dispatch:

permissions:
    contents: read
    packages: write
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Verify JSON file
              uses: netcracker/qubership-workflow-hub/actions/verify-json@main
              with:
                json-file: ${{ env.JSON_FILE }}
                schema-file: ${{ env.CONFIG_SCHEMA }}
              env:
                JSON_FILE: "./confit/org-mandatory-topcs/topics.json"
                CONFIG_SCHEMA: "./confit/org-mandatory-topcs/config-schema.json"

            - name: Package Cleanup
              uses: nookyo/qubership-workflow-hub/actions/package-cleanup@main
              env:
                PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_REPOSITORY: ${{ github.repository }}
                GITHUB_REF: ${{ github.ref }}
                GITHUB_RUN_ID: ${{ github.run_id }}
                GITHUB_RUN_NUMBER: ${{ github.run_number }}
                GITHUB_WORKFLOW: ${{ github.workflow }}
                GITHUB_ACTOR: ${{ github.actor }}
                GITHUB_EVENT_NAME: ${{ github.event_name }}
                GITHUB_EVENT_PATH: ${{ github.event_path }}

