name: Package Cleanup
on:
    workflow_dispatch:

permissions:
    contents: read
    packages: write
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Package Cleanup
              uses: nookyo/qubership-workflow-hub/actions/container-package-cleanup@main
              with:
                threshold-days: 1
                included-tags: ""
                excluded-tags: ""
                dry-run: true
              env:
                PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

